//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalkulatorPotrosnjeElektricneEnergije.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.114")]
        public double CijenaPotrosnjeVisaTarifaLJ {
            get {
                return ((double)(this["CijenaPotrosnjeVisaTarifaLJ"]));
            }
            set {
                this["CijenaPotrosnjeVisaTarifaLJ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.057")]
        public double CijenaPotrosnjeNizaTarifaLJ {
            get {
                return ((double)(this["CijenaPotrosnjeNizaTarifaLJ"]));
            }
            set {
                this["CijenaPotrosnjeNizaTarifaLJ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.0945")]
        public double CijenaPotrosnjeSrednjaTarifaLJ {
            get {
                return ((double)(this["CijenaPotrosnjeSrednjaTarifaLJ"]));
            }
            set {
                this["CijenaPotrosnjeSrednjaTarifaLJ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1486")]
        public double CijenaPotrosnjeVisaTarifaZ {
            get {
                return ((double)(this["CijenaPotrosnjeVisaTarifaZ"]));
            }
            set {
                this["CijenaPotrosnjeVisaTarifaZ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.0743")]
        public double CijenaPotrosnjeNizaTarifaZ {
            get {
                return ((double)(this["CijenaPotrosnjeNizaTarifaZ"]));
            }
            set {
                this["CijenaPotrosnjeNizaTarifaZ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1229")]
        public double CijenaPotrosnjeSrednjaTarifaZ {
            get {
                return ((double)(this["CijenaPotrosnjeSrednjaTarifaZ"]));
            }
            set {
                this["CijenaPotrosnjeSrednjaTarifaZ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4.67")]
        public double PretplataJednotarifnoBrojilo {
            get {
                return ((double)(this["PretplataJednotarifnoBrojilo"]));
            }
            set {
                this["PretplataJednotarifnoBrojilo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7.36")]
        public double PretplataDvotarifnoBrojilo {
            get {
                return ((double)(this["PretplataDvotarifnoBrojilo"]));
            }
            set {
                this["PretplataDvotarifnoBrojilo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.48")]
        public double NaknadaUslugaSnabdjevanja {
            get {
                return ((double)(this["NaknadaUslugaSnabdjevanja"]));
            }
            set {
                this["NaknadaUslugaSnabdjevanja"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.04")]
        public double NaknadaObnovljiviIzvori {
            get {
                return ((double)(this["NaknadaObnovljiviIzvori"]));
            }
            set {
                this["NaknadaObnovljiviIzvori"] = value;
            }
        }
    }
}
